spring:
  # Nacos配置中心！部署前需要修改
  cloud:
    nacos:
      config:
        server-addr: 127.0.0.1:8848 # 部署前请修改为对应的 Nacos 服务器地址
  config:
    import: optional:nacos:order-service-dev.properties # 可选:nacos:对应nacos的配置dataId
